### ISSUE TITLE
Possible Close and Flush Error

### ISSUE THREAD

**Issue by SilentBlueD666** [DixonDs/serilog-sinks-teams#4]
Hi, I been using this sink in a console app and have notice that if the application quits before the "Serilog.Sinks.PeriodicBatching" OnTick event has been run then the logs in the queue are lost.

After looking at the "MicrosoftTeamsSink.cs" I believe this maybe due to the order in which things are disposed, in the Dispose() method.

Currently the HttpClient is disposed first then the Base Dispose method is called where it tries to flush the buffer however I would assume this fails because the HttpClient is no longer valid, thus dropping the buffer.

I have tried to SelfLog to test this theory but noting is outputted to the temp file I created, which also leads me to believe that it may not even get to the Dispose method as well.

Any help would be great as really like this sink :)

**Comment by SilentBlueD666** [comment]
**Update**: Was able to get my self logging working correctly, as you can see below this maybe the problem I was talking about.

`2018-03-27T12:08:59.9966286Z Exception while emitting periodic batch from Serilog.Sinks.MicrosoftTeams.MicrosoftTeamsSink: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
   at System.Net.Http.HttpClient.CheckDisposed()
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Serilog.Sinks.MicrosoftTeams.MicrosoftTeamsSink.<EmitBatchAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.<OnTick>d__16.MoveNext()
2018-03-27T12:09:00.0046354Z Exception while emitting periodic batch from Serilog.Sinks.MicrosoftTeams.MicrosoftTeamsSink: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
   at System.Net.Http.HttpClient.CheckDisposed()
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Serilog.Sinks.MicrosoftTeams.MicrosoftTeamsSink.<EmitBatchAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.<OnTick>d__16.MoveNext()`

**Comment by SilentBlueD666** [comment]
I know how to fix it, just need access to submit the change.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DixonDs** [comment]
Hi @SilentBlueD666 and @ShareBuilderAustin! The change is now merged and published as 0.2.1: https://www.nuget.org/packages/Serilog.Sinks.MicrosoftTeams/0.2.1
